# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227d04a49a4573d4bf256e71d67836c7e7b446808000321490b028fd22be61d5a764a8f6e09042bfe083871d58ae588f4286d0f212862f4794a6b4d732d63e9d

test:
  secret_key_base: 2d0e2fe6396dbc9e8df0f794cc57e6475b6296cf16b44c0d90d7e875ba6d95873a5fec782ab58be2540eb7c5ee34ad14b5cc05b57901e656ce427eed2638341f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
